
var SLACK_CLIENT_ID = process.env.SLACK_CLIENT_ID || '';
var SLACK_SECRET = process.env.SLACK_SECRET || '';
var SLACK_TOKEN = process.env.SLACK_TOKEN || '';

var POSTGRES_USER = process.env.POSTGRES_USER || '';
var POSTGRES_DATABASE = process.env.POSTGRES_DATABASE || '';
var POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD || '';
var POSTGRES_HOST = process.env.POSTGRES_HOST || '';

exports.SLACK_CLIENT_ID = SLACK_CLIENT_ID;
exports.SLACK_SECRET = SLACK_SECRET;
exports.SLACK_TOKEN = SLACK_TOKEN;

exports.POSTGRES_USER = POSTGRES_USER;
exports.POSTGRES_DATABASE = POSTGRES_DATABASE;
exports.POSTGRES_PASSWORD = POSTGRES_PASSWORD;
exports.POSTGRES_HOST = POSTGRES_HOST;
